# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.3'

services:
  irepairbenet:
    image: irepairbenet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 22:5000
